FROM node:18

WORKDIR /calendar-gen

RUN mkdir -p ./app

COPY ./app/package.json ./app
COPY ./app/package-lock.json ./app

RUN cd ./app && npm install

COPY ./app ./app

RUN cd ./app && npm run build

EXPOSE 3000

CMD ["npm", "start"]