FROM debian:bookworm

RUN apt-get update && \
    apt-get install -y build-essential sqlite3 python3-pip python3-venv

RUN python3 -m venv env
ENV PATH="/env/bin/:$PATH"

WORKDIR /calendar-gen/backend

RUN apt-get update && \
    apt-get install -y build-essential wget tar

COPY ./backend/requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

COPY ./backend ./

EXPOSE 5000

CMD ["gunicorn", "wsgi:app", "--bind", "0.0.0.0:5000"]