FROM python:3.11-slim-buster

RUN apt-get update && \
    apt-get install -y build-essential

WORKDIR /calendar-gen

RUN mkdir -p ./backend

COPY ./backend/requirements.txt ./backend

RUN cd ./backend && pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

ENV FLASK_APP=main.py

CMD ["flask", "run", "--host=0.0.0.0"]
