version: '3'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.backend
        ports:
            - "5000:5000"
    frontend:
        build:
            context: .
            dockerfile: Dockerfile.frontend
        ports:
            - "3000:3000"