version: '3'
services:
    flask:
        build:
            context: .
            dockerfile: Dockerfile.backend
        ports:
            - "5000:5000"
    app:
        build:
            context: .
            dockerfile: Dockerfile.frontend
        ports:
            - "3000:3000"